version: '3'

networks:
  scheduler:
    driver: bridge

volumes:
  postgres:
  pgadmin:

services:

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_HOST:${DATABASE_HOST:-localhost}
      - DLOAD:${DLOAD:-10}
      - FREQ:${FREQ:-1}
      - POSTGRES_USER:${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD:-changeme}
      - DATABASE_NAME:${DATABASE_NAME:-scheduler}
      - DATABASE_PORT:${DATABASE_PORT:-5432}
    ports:
      - ${BACKEND_PORT:-8080}:3000
    networks:
      - scheduler
    env_file:
      - .env

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${DATABASE_NAME:-scheduler}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${DATABASE_PORT:-5432}:3030"
    networks:
      - scheduler
    restart: unless-stopped   

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - scheduler
    restart: unless-stopped